### ISSUE TITLE
Publish new NPM with latest changes

### ISSUE THREAD

**Issue by soeffing** [clairton/ember-cli-maskmoney#4]
Hi, I just noticed that the latest changes, such as the implementation of observing the value and updated the `number` parameter accordingly, have not been published. Would you mind to release a new NPM with those changes?

Thanks

**Comment by clairton** [comment]
Hi, sorry for the delay @soeffing ,  I requested permission in npm for @thiagoc7, When he answers we publish.
For now, you use in your package.json as "ember-cli-maskmoney": "clairton/ember-cli-maskmoney#master".

**Comment by thiagoc7** [comment]
@clairton, please test if you can `npm publish`

**Comment by clairton** [comment]
Thanks @thiagoc7.

@soeffing the new version is available at npm.

I close this issue!
